const fs = require('fs');
const he = JSON.parse(fs.readFileSync('locales/he.json', 'utf8'));

he.support.sections[1].items[4].answer.message = "<p>פתחו את <strong>הגדרות</strong> ב-Pushanova והפעילו את <strong>הקש כדי לספור</strong>. במהלך אימון, כל הקשה על מסך האימון סופרת שכיבת סמיכה אחת.</p>";
he.support.sections[1].items[5].answer.message = "<p>ניתן לתקן את מספר שכיבות הסמיכה בסטים שכבר קיימים. פתחו את האימון, הקישו על <strong>עריכה</strong> בתרשים שכיבות הסמיכה, שנו את ספירות הסטים, והקישו על <strong>שמירה</strong>.</p><p>העריכה אינה מוסיפה סט נוסף לאימון. כדי לתעד עבודה נוספת כמפגש נפרד, פתחו את <strong>אימונים</strong>, הקישו על <strong>הוספת אימון</strong>, והזינו את הסטים ידנית.</p>";
he.support.sections[2].items[1].answer.message = "<p>ב-iPhone, פתחו את <strong>הגדרות</strong> ב-Pushanova והפעילו את <strong>שימוש ב-Apple Watch</strong>. ודאו ש-Pushanova מותקנת ב-Watch ושה-Watch פתוח ונמצא בקרבת מקום. לאחר מכן, התחילו את האימון ב-iPhone או ב-Apple Watch.</p><p>ה-Apple Watch סופר את שכיבות הסמיכה שלכם בעוד ה-iPhone מציג את אותו האימון. ספירת שכיבות הסמיכה, סטים, קצב, ומנוחה נשארים מסונכרנים.</p><p>אימוני Apple Watch מצומדים זמינים עם iPhone, לא עם iPad.</p>";
he.support.sections[4].items[1].answer.message = "<p>לרוב כן. פתחו מחדש את Pushanova ועקבו אחר הודעת השחזור. ב-Apple Watch, עשוי להופיע <strong>Workout Interrupted</strong> או התראה דומה, ושחרור ההודעה שומר את החלק שהושלם במידת האפשר.</p><p>ייתכן שלא יהיה ניתן לשחזר כאשר האימון השמור פגום, ישן מדי, או שלמכשיר אין מספיק שטח אחסון פנוי. אם הבעיה נמשכת:</p><ul><li>עדכנו את Pushanova ואת מערכת ההפעלה של המכשיר.</li><li>הפעילו מחדש את המכשיר.</li><li>אשרו שלמכשיר יש שטח אחסון פנוי.</li><li>אל תסגרו את Pushanova בזמן ש<strong>סיום אימון</strong> נשמר.</li></ul>";
he.support.sections[4].items[3].answer.message = "<p>ב-iPhone או ב-iPad:</p><ul><li>פתחו את <strong>אימונים</strong> כדי לצפות באימונים בודדים, סטים, משך זמן, קלוריות, הערות ופרטים זמינים.</li><li>פתחו את <strong>התקדמות</strong> כדי לצפות בסך הכל מאז ומעולם, עקביות לאחרונה, הסט הגבוה ביותר שלכם ותרשימים זמינים.</li><li>פתחו את <strong>Calendar</strong> כדי לצפות באימונים לפי תאריך. לוח השנה דורש Pushanova Premium.</li></ul><p>Pushanova Premium כולל גם השוואות שבועיות, תרשימי התקדמות מפורטים, ופרטים נוספים על קצב, תדירות ודופק.</p><p>Apple Watch מציג סיכום מיד לאחר האימון. היסטוריה והתקדמות מלאות זמינות ב-iPhone וב-iPad.</p>";
he.support.sections[4].items[4].answer.message = "<p>פתחו את <strong>בחירת רמה</strong> ב-iPhone, ב-iPad, או ב-Apple Watch. בחרו כל רמה זמינה.</p><p>השלמת שכיבות הסמיכה הנדרשות מקדמת את התוכנית לרמה הבאה. תוכלו גם לחזור על רמה או לדלג לרמה אחרת. רמות 11–50 דורשות Pushanova Premium.</p>";
he.support.sections[5].items[0].answer.message = "<p>התכונות הבאות הן בחינם:</p><ul><li>רמות תוכנית 1–10</li><li>אימון ללא יעדים מוגדרים מראש</li><li>ספירה אוטומטית והקש כדי לספור</li><li>הזנת אימון ידנית</li><li>היסטוריית אימונים, הערות ושיתוף</li><li>עקביות אימונים לאחרונה, סך הכל מאז ומעולם והסט הגבוה ביותר שלכם</li><li>מידע אימון חי במסך הנעילה וב-Dynamic Island</li><li>תזכורות לאימון</li><li>Apple Health וסנכרון iCloud</li></ul><p>Pushanova Premium פותח את רמות התוכנית 11–50, לוח שנת האימונים, השוואות שבועיות, תרשימי התקדמות מפורטים ופרטי אימון נוספים.</p>";
he.support.sections[5].items[1].answer.message = "<p>פתחו את מסך Pushanova Premium והקישו על <strong>שחזור רכישה</strong>. השתמשו באותו Apple Account שבו נרכש המינוי השנתי או הרכישה לכל החיים.</p><p>רכישות מעובדות על ידי Apple. ל-Pushanova אין חשבון משלה לרכישות.</p>";
he.support.sections[5].items[2].answer.message = "<ol><li>אשרו שהמכשיר משתמש ב-Apple Account שביצע את הרכישה.</li><li>אשרו שלמכשיר יש חיבור לאינטרנט.</li><li>פתחו את מסך Pushanova Premium והקישו על <strong>שחזור רכישה</strong>.</li><li>סגרו ופתחו מחדש את Pushanova.</li><li>בדקו שרכישות בתוך היישום מותרות במכשיר.</li></ol><p>אם ה-Premium עדיין נעול, שלחו דוא״ל אל <a href=\"{mailto}\">{email}</a>. כללו את דגם המכשיר, גרסת Pushanova, סוג הרכישה וצילום מסך המציג את הרכישה או השגיאה. הסתירו מידע אישי או פרטי תשלום שאינם קשורים.</p>";
he.support.sections[5].items[4].answer.message = "<p>פתחו את <strong>מינויים</strong> בהגדרות ה-Apple Account שלכם ובחרו ב-Pushanova.</p><p>ביטול עוצר את החידוש הבא. זה בדרך כלל לא מעניק החזר עבור תקופת המינוי הנוכחית. אימונים שמורים יישארו זמינים. תכונות ה-Premium ננעלות כשתקופת התשלום מסתיימת אלא אם תרכשו מחדש Premium, תממשו הטבה בתוקף, או שאתם בעלים של הרכישה לכל החיים.</p>";
he.support.sections[5].items[5].answer.message = "<p>Apple מעבדת את כל רכישות והחזרי Pushanova. בקשו החזר בכתובת <a href=\"{refundUrl}\">reportaproblem.apple.com</a> או דרך היסטוריית הרכישות שלכם ב-Apple.</p><p>מפתח Pushanova אינו יכול להנפיק החזר מה-App Store.</p>";
he.support.sections[5].items[6].answer.message = "<p>כן. השתמשו באותו Apple Account במכשיר האחר והקישו על <strong>שחזור רכישה</strong> ב-Pushanova.</p><p>Family Sharing לא מופעל עבור Pushanova Premium.</p>";
he.support.sections[5].items[7].answer.message = "<p>הקישו על <strong>שחזור רכישה</strong> כדי לשחזר את Premium עבור ה-Apple Account הרוכש.</p><p>אם סנכרון iCloud הופעל, היסטוריית אימונים שנשמרה ב-iCloud יכולה להסתנכרן לאחר התקנה מחדש. ללא סנכרון iCloud, הסרת Pushanova מוחקת את היסטוריית האימונים שנשמרה רק באותו מכשיר.</p><p>עותקי Apple Health נשארים ב-Apple Health עד שימחקו משם.</p>";

fs.writeFileSync('locales/he.json', JSON.stringify(he, null, 2));
