const fs = require('fs');

const en = JSON.parse(fs.readFileSync('locales/en.json', 'utf8'));

const translations = {
  "meta.code": "he",
  "meta.name": "עברית",
  "meta.dir": "rtl",
  "meta.ogLocale": "he_IL",
  "meta.ogImageAlt": "סמליל Pushanova",
  "nav.home": "Club Pushanova",
  "nav.features": "תכונות",
  "nav.support": "תמיכה",
  "footer.home": "Club Pushanova",
  "footer.features": "תכונות",
  "footer.terms": "תנאים",
  "footer.privacy": "פרטיות",
  "footer.support": "תמיכה",
  "footer.pressKit": "ערכת עיתונות",
  "footer.instagram": "אינסטגרם",
  "footer.about": "אודות המפתח",
  "footer.heartRateNote": "1. מדידת דופק עם AirPods Pro 3 או Powerbeats Pro 2 זמינה ב-Pushanova ב-iPhone עם iOS 26 ואילך, וב-iPad עם iPadOS 26 ואילך. נתוני דופק זמינים גם דרך מד דופק Bluetooth המחובר ל-iPhone או ל-iPad.",
  "footer.copyright": "זכויות יוצרים © 2026 יבגני בוגדנוביץ'. כל הזכויות שמורות.",
  "notFound.meta.title": "העמוד לא נמצא · Pushanova",
  "notFound.meta.description": "עמוד זה אינו זמין.",
  "notFound.h1": "העמוד לא נמצא",
  "notFound.lead": "עמוד זה אינו זמין.",
  "notFound.homeLink": "Club Pushanova",
  "languages.meta.title": "בחירת שפה · Pushanova",
  "languages.meta.description": "בחרו שפה עבור אתר Pushanova.",
  "languages.h1": "בחירת שפה",
  
  "home.meta.title": "מונה שכיבות סמיכה עבור iPhone, iPad, ו-Apple Watch · Pushanova",
  "home.meta.description": "מונה שכיבות סמיכה עבור iPhone, iPad, ו-Apple Watch. התקדמו לעבר 100 שכיבות סמיכה, או התאמנו באופן חופשי.",
  "home.meta.ogTitle": "Pushanova",
  "home.meta.ogDescription": "מונה שכיבות סמיכה שמכין אתכם ל-100 שכיבות סמיכה. ספירה אוטומטית ב-iPhone, ב-iPad וב-Apple Watch.",
  "home.eyebrow": "אימון שכיבות סמיכה עבור iPhone, iPad, ו-Apple Watch",
  "home.h1": "התקדמו לעבר 100 שכיבות סמיכה בקצב שלכם",
  "home.hero.alt": "iPhone מציג את יישום Pushanova",
  "home.lead": "עקבו אחר התוכנית או התאמנו באופן חופשי. Pushanova סופרת את שכיבות הסמיכה שלכם ב-iPhone, ב-iPad וב-Apple Watch.",
  "home.download": "הורד ב-App Store",
  "home.offer": "חינם להתחלה. ללא חשבון. ללא פרסומות.",
  
  "home.start.h2": "התחילו מהיכן שאתם נמצאים",
  "home.start.alt": "iPhone מציג את רמות התוכנית של Pushanova",
  "home.start.paragraphs.0": "התוכנית כוללת 50 רמות. התחילו בכל רמה, או התאמנו באופן חופשי ובחרו את הסטים שלכם בעצמכם. תוכלו גם לתעד סטים של שכיבות סמיכה במהלך אימוני סיבולת לב-ריאה או כוח.",
  "home.start.paragraphs.1": "Pushanova אינה דורשת לוח זמנים יומי או שבועי. ניתן לחזור על רמה ולקחת ימי מנוחה, ללא קנס על הפסקה.",
  
  "home.how.h2": "איך Pushanova עובדת",
  "home.how.alt": "iPhone ו-Apple Watch מציגים אימון ב-Pushanova",
  "home.how.steps.0.heading": "התחלה",
  "home.how.steps.0.paragraphs.0": "הניחו את ה-iPhone או ה-iPad שלכם על הרצפה, או התחילו ב-Apple Watch. ספירה קצרה לאחור תיתן לכם זמן להיכנס לתנוחה.",
  "home.how.steps.1.heading": "אימון",
  "home.how.steps.1.paragraphs.0": "Pushanova סופרת את שכיבות הסמיכה שלכם באופן אוטומטי ומתעדת סטים, קצב, זמן וקלוריות. אתם קובעים כמה זמן לנוח: להמשיך מוקדם יותר או לנוח יותר זמן.",
  "home.how.steps.2.heading": "אימון ב-Apple Watch",
  "home.how.steps.2.paragraphs.0": "התחילו וסיימו אימון ב-Apple Watch גם כשאין iPhone בקרבת מקום. בשילוב יחד, ה-Apple Watch סופר בעוד ה-iPhone מציג את אותו אימון.",
  "home.how.steps.3.heading": "סקירה",
  "home.how.steps.3.paragraphs.0": "Pushanova שומרת כל אימון שהושלם. ההיסטוריה שלכם מראה כיצד האימונים משתנים לאורך זמן.",
  "home.how.featuresLink": "לכל התכונות",
  
  "home.reviews.h2": "מה המשתמשים אומרים",
  "home.reviews.rating": "★★★★★",
  "home.reviews.items.0.title": "יישום מדהים",
  "home.reviews.items.0.byline": "2 באפריל, 2026 — Hellfire7777",
  "home.reviews.items.0.place": "הודו",
  "home.reviews.items.0.quote": "״אני ממש אוהב את היישום הזה. הפשטות שלו היא מה שעושה אותו לטוב ביותר!״",
  "home.reviews.items.1.title": "טוב",
  "home.reviews.items.1.byline": "19 ביוני, 2024 — Rikstarrr124",
  "home.reviews.items.1.place": "אוסטרליה",
  "home.reviews.items.1.quote": "״זה מעולה. זה עוזר לי לעשות יותר שכיבות סמיכה, וזה מניע אותי להמשיך להשתפר.״",
  "home.reviews.items.2.title": "מדהים",
  "home.reviews.items.2.byline": "12 בינואר, 2025 — AnonymousfromME",
  "home.reviews.items.2.place": "ארצות הברית",
  "home.reviews.items.2.quote": "״אני יכול לעשות כל כך הרבה שכיבות סמיכה עכשיו! נכתב על ידי הבן שלנו בן ה-13, שקיבל המון מוטיבציה מהיישום הזה.״",
  "home.reviews.items.3.title": "יישום שכיבות סמיכה נהדר",
  "home.reviews.items.3.byline": "15 במאי, 2025 — c15co",
  "home.reviews.items.3.place": "אוסטרליה",
  "home.reviews.items.3.quote": "״אני אוהב את היישום הזה. לאחרונה החלטתי לבדוק כמה מהר אוכל להגיע ל-100 שכיבות סמיכה. לא הצלחתי למצוא יישום שהופך את זה לקל במחיר נוח עד שמצאתי את זה. אני אוהב כמה שהיישום נקי. המפתח גם מגיב מאוד למשוב.״",
  "home.reviews.note": "ביקורות מה-App Store נערכו קלות לשם אורך ובהירות.",
  
  "home.privacy.h2": "פרטיות ואמינות",
  "home.privacy.paragraphs.0": "מעקב אחר שכיבות סמיכה ב-iPhone וב-iPad אינו מצלם תמונות ואינו מקליט, שומר או מעלה וידאו. Pushanova אינה משתמשת במצלמה כדי לזהות אתכם.",
  "home.privacy.paragraphs.1": "Pushanova אינה דורשת חשבון, אינה מוכרת את הנתונים שלכם ואינה מכילה פרסומות. נתוני האימון נשארים במכשירים שלכם ובחשבון ה-iCloud האישי שלכם כאשר הסנכרון מופעל. באישורכם, אימונים שהושלמו יכולים להישמר ב-Apple Health.",
  "home.privacy.paragraphs.2": "ניתן לשחזר אימון פעיל אם Pushanova נסגרת או מופרעת.",
  
  "home.qna.h2": "שאלות ותשובות",
  "home.qna.items.0.question": "האם אני צריך Apple Watch כדי להשתמש ב-Pushanova?",
  "home.qna.items.0.paragraphs.0": "לא. Pushanova יכולה לעקוב אחר שכיבות סמיכה עם iPhone או iPad. ה-Apple Watch מוסיף מעקב מבוסס-פרק כף היד ותומך בשכיבות סמיכה מוגבהות על ספסלים ומוטות אופקיים.",
  "home.qna.items.1.question": "האם אוכל להתאמן ב-Apple Watch ללא ה-iPhone בקרבת מקום?",
  "home.qna.items.1.paragraphs.0": "כן. ניתן להתחיל ולסיים אימון ב-Apple Watch בזמן שה-iPhone שלכם אינו בקרבת מקום. היישום ב-Watch מתמקד באימונים. היסטוריית אימונים וניתוח נתונים זמינים ב-iPhone וב-iPad.",
  "home.qna.items.1.paragraphs.1": "כאשר משתמשים ב-Apple Watch וב-iPhone יחד, ה-Apple Watch יכול לעקוב אחר שכיבות הסמיכה שלכם בעוד ה-iPhone מציג את האימון המסונכרן.",
  "home.qna.items.2.question": "כיצד Pushanova סופרת שכיבות סמיכה?",
  "home.qna.items.2.paragraphs.0": "ב-iPhone וב-iPad, המצלמה הקדמית מודדת שינויים במרחק שבין הפנים שלכם למכשיר. ב-Apple Watch, Pushanova מנתחת את התנועה של פרק כף היד שלכם. תוכלו גם להפעיל הגדרה שסופרת שכיבת סמיכה אחת בכל פעם שאתם מקישים על המסך.",
  "home.qna.items.3.question": "האם אוכל להשתמש ב-Pushanova ללא הרשאת גישה למצלמה?",
  "home.qna.items.3.paragraphs.0": "כן. ב-iPhone, Pushanova יכולה להשתמש בחיישן מובנה אחר כאשר גישה למצלמה אינה זמינה. גם ב-iPhone וגם ב-iPad, ניתן להפעיל ספירה באמצעות הקשה על המסך. Apple Watch אינו משתמש במצלמה.",
  "home.qna.items.4.question": "האם Pushanova מקליטה או מעלה תמונות או וידאו בזמן ספירת שכיבות סמיכה?",
  "home.qna.items.4.paragraphs.0": "לא. ספירה אוטומטית אינה מצלמת תמונות ואינה מקליטה, שומרת או מעלה וידאו. המצלמה רק מודדת מרחק, ו-Pushanova אינה משתמשת בה כדי לזהות אתכם.",
  "home.qna.items.5.question": "באילו סוגים של שכיבות סמיכה יש תמיכה?",
  "home.qna.items.5.paragraphs.0": "iPhone ו-iPad תומכים בשכיבות סמיכה רגילות על הרצפה ובשכיבות סמיכה מהברכיים. Apple Watch תומך גם בשכיבות סמיכה מוגבהות על ספסל או מוט אופקי.",
  "home.qna.items.5.paragraphs.1": "שכיבות סמיכה על ידיות מקבילות עם כפות הידיים פונות זו לזו אינן נתמכות. שכיבות סמיכה על האגרופים עשויות לעבוד, אך הספירה עלולה להיות פחות מדויקת.",
  "home.qna.items.6.question": "האם Pushanova תספור כל שכיבת סמיכה נכון?",
  "home.qna.items.6.paragraphs.0": "אף שיטת מעקב אוטומטית אינה יכולה לספור כל תנועה נכון. מיקום המכשיר, היציבה והמהירות יכולים להשפיע על התוצאה. לאחר האימון, תוכלו לתקן את מספר שכיבות הסמיכה בכל סט קיים.",
  "home.qna.items.7.question": "מה אם אני עדיין לא יכול לבצע שכיבת סמיכה אחת מלאה?",
  "home.qna.items.7.paragraphs.0": "תוכלו להתחיל ברמות הראשונות, שמכילות סטים קטנים. יש תמיכה בשכיבות סמיכה מהברכיים. ניתן לחזור על רמה ולהתקדם בקצב שלכם.",
  "home.qna.items.8.question": "האם מתאמנים מנוסים יכולים להשתמש ב-Pushanova עם אימונים אחרים?",
  "home.qna.items.8.paragraphs.0": "כן. ניתן להתחיל בכל רמה או להתאמן באופן חופשי. Pushanova יכולה לתעד סטים של שכיבות סמיכה במהלך אימוני סיבולת לב-ריאה או כוח.",
  "home.qna.items.9.question": "מהי תוכנית 100 שכיבות הסמיכה של Pushanova?",
  "home.qna.items.9.paragraphs.0": "התוכנית כוללת 50 רמות בשלושה שלבים. כל רמה היא אימון מובנה עם סטים ויעדים של שכיבות סמיכה מוגדרים מראש. הרמה האחרונה היא סט אחד של 100 שכיבות סמיכה.",
  "home.qna.items.9.paragraphs.1": "ניתן להתחיל בכל רמה, לחזור על רמה או לדלג לרמה אחרת. 10 הרמות הראשונות הן בחינם. Pushanova Premium פותח את רמות 11–50.",
  "home.qna.items.10.question": "האם אוכל להשלים רמות וגם להתאמן באופן חופשי?",
  "home.qna.items.10.paragraphs.0": "כן. ניתן להשלים רמה באימון אחד ולהתאמן באופן חופשי באימון אחר. תוכלו גם להמשיך להתאמן באופן חופשי לאחר השלמת רמה באותו אימון.",
  "home.qna.items.11.question": "האם אוכל להתאמן בקצב שלי ולקחת ימי מנוחה?",
  "home.qna.items.11.paragraphs.0": "כן. Pushanova אינה דורשת לוח זמנים יומי או שבועי. ניתן לחזור על רמות, לקחת ימי מנוחה ולחזור לתוכנית כשאתם מוכנים.",
  "home.qna.items.11.paragraphs.1": "במהלך אימון של רמה, Pushanova מציעה 90 שניות של מנוחה בין סטים מתוכננים. תוכלו להמשיך מוקדם יותר או לנוח יותר זמן. כשאתם מתאמנים באופן חופשי, אין יעד מנוחה קבוע.",
  "home.qna.items.12.question": "האם אוכל ליצור אימון מותאם אישית?",
  "home.qna.items.12.paragraphs.0": "לא ניתן לבנות ולשמור רצף מוגדר מראש של סטים לפני אימון. כשאתם מתאמנים באופן חופשי, אתם מחליטים כמה שכיבות סמיכה וסטים לבצע תוך כדי האימון, ו-Pushanova מתעדת את האימון.",
  "home.qna.items.13.question": "האם Pushanova עובדת עם Apple Health?",
  "home.qna.items.13.paragraphs.0": "כן. באישורכם, Pushanova שומרת אימוני כוח שהושלמו ב-Apple Health, כולל משך זמן, קלוריות פעילות, ודופק כאשר הוא זמין. ספירת שכיבות סמיכה וסטים אינה נשמרת ב-Apple Health.",
  "home.qna.items.13.paragraphs.1": "הרשאת Apple Health נדרשת לאימונים ב-Apple Watch. היא אופציונלית ב-iPhone וב-iPad.",
  "home.qna.items.14.question": "האם Pushanova עוקבת אחר דופק וקלוריות?",
  "home.qna.items.14.paragraphs.0": "כן. Pushanova מעריכה קלוריות פעילות גם כאשר אין מד דופק זמין. הדופק יכול להגיע מ-Apple Watch, מאוזניות תומכות מד דופק או ממד דופק Bluetooth.",
  "home.qna.items.14.paragraphs.1": "מדידת דופק עם אוזניות תומכות דורשת iOS 26 ואילך ב-iPhone, או iPadOS 26 ואילך ב-iPad.",
  "home.qna.items.15.question": "האם Pushanova זמינה ב-iPad?",
  "home.qna.items.15.paragraphs.0": "כן. Pushanova היא יישום iPad מלא עם ספירה אוטומטית, תוכנית 100 שכיבות סמיכה, אפשרות להתאמן באופן חופשי, היסטוריית אימונים, התקדמות, ניתוח נתונים, ו-Apple Health.",
  "home.qna.items.16.question": "האם Pushanova עובדת ללא חיבור לאינטרנט?",
  "home.qna.items.16.paragraphs.0": "כן. ניתן להתחיל ולשמור אימון ללא חיבור לאינטרנט. סנכרון iCloud מתחדש כאשר המכשיר שלכם מחובר שוב. רכישות ב-App Store דורשות חיבור לאינטרנט.",
  "home.qna.items.17.question": "האם אני צריך חשבון או מינוי?",
  "home.qna.items.17.paragraphs.0": "לא. Pushanova אינה דורשת חשבון או מינוי. ניתן להשתמש ביישום מבלי לספק כתובת דוא״ל או ליצור סיסמה. Pushanova Premium היא אופציונלית ונרכשת דרך ה-App Store.",
  "home.qna.items.18.question": "האם אוכל להשתמש ב-Pushanova בחינם?",
  "home.qna.items.18.paragraphs.0": "כן. האימון החינמי כולל אימונים ללא הגבלה וללא יעדים מוגדרים מראש, 10 הרמות הראשונות, וספירה אוטומטית ב-iPhone, ב-iPad וב-Apple Watch. Pushanova אינה מכילה פרסומות.",
  "home.qna.items.19.question": "מה כוללת Pushanova Premium?",
  "home.qna.items.19.paragraphs.0": "Pushanova Premium פותח את רמות 11–50 ודרכים נוספות לסקור את ההתקדמות שלכם. אלה כוללים לוח שנת אימונים, השוואות שבועיות, תרשימי התקדמות מפורטים, ופרטים נוספים על קצב, תדירות ודופק עבור כל אימון.",
  "home.qna.items.19.paragraphs.1": "Pushanova Premium זמינה כמינוי שנתי או כרכישה לכל החיים.",
  "home.qna.items.20.question": "האם Pushanova מציעה תקופת ניסיון בחינם?",
  "home.qna.items.20.paragraphs.0": "מנויים חדשים זכאים יכולים לנסות את המינוי השנתי בחינם למשך שלושה ימים. המינוי מתחיל אוטומטית אלא אם תבטלו לפני תום תקופת הניסיון. רכישה לכל החיים אינה כוללת תקופת ניסיון, וה-App Store מציג את המחיר לפני הרכישה.",
  
  "home.closing.h2": "מוכנים לאימון הראשון שלכם?",
  "home.closing.alt": "אישה נחה במצב כריעה עם Pushanova ב-Apple Watch שלה",
  "home.closing.lead": "תוכלו להתאמן באופן חופשי למשך כמה זמן שתרצו. 10 הרמות הראשונות והספירה האוטומטית הן גם בחינם. התחילו אימון ב-iPhone, ב-iPad או ב-Apple Watch.",
  "home.closing.offer": "ללא חשבון. אין צורך במינוי. ללא פרסומות.",
  
  "features.meta.title": "תוכנית של 100 שכיבות סמיכה וספירה אוטומטית · Pushanova",
  "features.meta.description": "תוכנית של 100 שכיבות סמיכה עם 50 רמות, ואימון ללא יעדים מוגדרים מראש. Pushanova סופרת שכיבות סמיכה ב-iPhone, ב-iPad וב-Apple Watch.",
  "features.h1": "עקבו אחר תוכנית ל-100 שכיבות סמיכה, או התאמנו באופן חופשי",
  "features.lead": "התוכנית מסתיימת בסט אחד של 100 שכיבות סמיכה. תוכלו גם להתאמן באופן חופשי, ו-Pushanova סופרת את האימון ב-iPhone, ב-iPad וב-Apple Watch.",
  "features.download": "הורד ב-App Store",
  "features.offer": "חינם להתחלה. ללא חשבון. ללא פרסומות.",
  "features.hero.alt": "Apple Watch מציג את Pushanova סופרת שכיבות סמיכה",
  
  "features.program.h2": "עקבו אחר התוכנית והתאמנו באופן חופשי",
  "features.program.alt": "iPhone מציג את רמות התוכנית של Pushanova",
  "features.program.paragraphs.0": "התוכנית כוללת 50 רמות בשלושה שלבים. התחילו בכל רמה. הרמה האחרונה היא סט אחד של 100 שכיבות סמיכה.",
  "features.program.paragraphs.1": "התאמנו באופן חופשי כשאתם לא רוצים יעדים מוגדרים מראש. אתם בוחרים את שכיבות הסמיכה והסטים, ותוכלו לחזור לתוכנית לאימון הבא.",
  "features.program.paragraphs.2": "10 הרמות הראשונות הן בחינם. Pushanova Premium פותח את רמות 11–50.",
  
  "features.counting.h2": "ספירת שכיבות סמיכה אוטומטית",
  "features.counting.alt": "iPhone מציג את Pushanova סופרת שכיבות סמיכה במהלך אימון",
  "features.counting.paragraphs.0": "ב-iPhone וב-iPad, הניחו את המכשיר על הרצפה ובצעו שכיבות סמיכה לכיוון המצלמה הקדמית. Pushanova סופרת את שכיבות הסמיכה שלכם בזמן שאתם זזים. ספירה אוטומטית אינה מצלמת תמונות או מקליטה וידאו.",
  "features.counting.paragraphs.1": "ב-Apple Watch, Pushanova סופרת שכיבות סמיכה מתוך תנועת פרק כף היד שלכם. זה תומך בשכיבות סמיכה על הרצפה ובשכיבות סמיכה מוגבהות על ספסלים ומוטות אופקיים.",
  "features.counting.paragraphs.2": "ניתן גם לספור שכיבת סמיכה אחת בכל פעם שאתם מקישים על המסך. אם השלמתם אימון ללא Pushanova, תוכלו להזין את הסטים וספירת שכיבות הסמיכה ידנית ב-iPhone או ב-iPad.",
  
  "features.watch.h2": "התאמנו ב-Apple Watch עם או בלי ה-iPhone שלכם",
  "features.watch.alt": "iPhone ו-Apple Watch מציגים אימון ב-Pushanova",
  "features.watch.sections.0.heading": "השלימו אימון ב-Apple Watch",
  "features.watch.sections.0.paragraphs.0": "התחילו והשלימו אימון ב-Apple Watch ללא ה-iPhone בקרבת מקום. היישום ב-Watch סופר את שכיבות הסמיכה שלכם ומציג את שלב האימון הנוכחי, מספר שכיבות הסמיכה, הסט, טיימר, קצב, דופק וקלוריות פעילות.",
  "features.watch.sections.0.paragraphs.1": "משוב הפטי מאשר שכיבות סמיכה וסטים שהושלמו, כך שאין צורך להסתכל על המסך לאחר כל תנועה.",
  "features.watch.sections.0.paragraphs.2": "ניתן להאזין למוזיקה או לפודקאסטים ולשלוט במדיה מה-Apple Watch במהלך אימון.",
  "features.watch.sections.1.heading": "השתמשו ב-Apple Watch וב-iPhone יחד",
  "features.watch.sections.1.paragraphs.0": "התחילו אימון באחד המכשירים. ה-Apple Watch יכול לספור את שכיבות הסמיכה שלכם בעוד ה-iPhone מציג את אותו אימון. ספירת שכיבות הסמיכה, סטים, קצב, מנוחה ומידע אימון אחר נשארים מסונכרנים.",
  
  "features.live.h2": "צפו במידע על האימון בזמן שאתם מתאמנים",
  "features.live.alt": "Apple Watch מציג דופק, קלוריות וקצב ב-Pushanova",
  "features.live.paragraphs.0": "במהלך אימון, Pushanova מציגה את השלב הנוכחי, מספר שכיבות הסמיכה והסט שלכם, טיימר, קצב, קלוריות פעילות, ודופק<sup>1</sup> כאשר הוא זמין.",
  "features.live.paragraphs.1": "ב-iPhone, השלב, הטיימר, הספירה והסט נשארים על מסך הנעילה וב-Dynamic Island. הסט הטוב ביותר שלכם הוא שיא אישי ואינו מושווה לאנשים אחרים.",
  
  "features.progress.h2": "סקרו את האימונים וההתקדמות שלכם",
  "features.progress.alt": "iPhone מציג את מסך התקדמות ב-Pushanova",
  "features.progress.sections.0.heading": "פרטי אימון",
  "features.progress.sections.0.paragraphs.0": "צפו בסטים, זמנים, קצב, דופק, וקלוריות פעילות עבור כל אימון שהושלם. שנו את ספירת שכיבות הסמיכה של הסטים אם יש צורך לאחר האימון.",
  "features.progress.sections.1.heading": "התקדמות לאורך זמן",
  "features.progress.sections.1.paragraphs.0": "עקבו אחר מספר שכיבות הסמיכה, האימונים, והסט הטוב ביותר שלכם. צפו כיצד הקצב, משך הזמן והתדירות שלכם משתנים על פני שבועות, חודשים ושנים.",
  "features.progress.sections.2.heading": "שיאים והישגים",
  "features.progress.sections.2.paragraphs.0": "Pushanova חוגגת ציוני דרך ללא דירוגים ורצפי ענישה. השיאים האישיים שלכם לאימון הטוב ביותר ולסט הטוב ביותר מעודכנים אוטומטית.",
  
  "features.devices.h2": "נועד עבור iPhone, iPad, ו-Apple Watch",
  "features.devices.paragraphs.0": "Pushanova מתוכנן כיישום מקומי עבור הפלטפורמות של Apple. הוא תומך במצב כהה, גודל טקסט דינמי, וסינכרון iCloud מהיר.",
  "features.devices.paragraphs.1": "ב-iPhone, פעילויות חיות עוזרות לכם לעקוב אחר האימון שלכם כאשר Pushanova סגורה. ווידג׳טים מציגים את ההתקדמות שלכם במסך הבית ובמסך הנעילה.",
  "features.devices.paragraphs.2": "ב-iPad, Pushanova היא יישום מלא המשתמש במסך הגדול כדי להציג היסטוריית אימונים, תרשימים והתקדמות לצידם.",
  "features.devices.paragraphs.3": "ב-Apple Watch, Pushanova פועלת באופן עצמאי כדי לעקוב אחר שכיבות סמיכה, דופק, וקלוריות פעילות. ווידג׳טים שומרים על הספירה הכוללת שלכם במרחק לחיצה אחת.",
  
  "features.pricing.h2": "תמחור פשוט ושקוף",
  "features.pricing.free.h3": "חינם",
  "features.pricing.free.items.0": "ספירה אוטומטית",
  "features.pricing.free.items.1": "אימונים חופשיים ללא הגבלה",
  "features.pricing.free.items.2": "10 רמות התוכנית הראשונות",
  "features.pricing.free.items.3": "שימוש ב-Apple Watch וה-iPhone יחד",
  "features.pricing.free.items.4": "יישום Apple Watch עצמאי",
  "features.pricing.free.items.5": "היסטוריית אימונים וסיכומים",
  "features.pricing.free.items.6": "סנכרון Apple Health",
  "features.pricing.free.items.7": "סנכרון iCloud מאובטח",
  "features.pricing.free.items.8": "ווידג׳טים ופעילויות חיות",
  "features.pricing.free.items.9": "ללא פרסומות",
  
  "features.pricing.premium.h3": "Pushanova Premium",
  "features.pricing.premium.items.0": "פתיחת רמות התוכנית 11–50",
  "features.pricing.premium.items.1": "לוח שנת אימונים והשוואות",
  "features.pricing.premium.items.2": "תרשימי היסטוריה והתקדמות",
  "features.pricing.premium.items.3": "ניתוח דופק וקצב",
  "features.pricing.premium.items.4": "תמיכה במפתח בודד",
  "features.pricing.premium.note": "Pushanova Premium זמינה כמינוי שנתי או כרכישה לכל החיים.",
  
  "features.closing.h2": "התחילו את האימון הראשון שלכם",
  "features.closing.alt": "iPhone מציג את מסך ההתחלה של Pushanova",
  "features.closing.lead": "התאמנו באופן חופשי למשך כמה זמן שתרצו או התחילו באחת מ-10 רמות התוכנית הראשונות. ספירה אוטומטית היא בחינם ב-iPhone, ב-iPad וב-Apple Watch.",
  "features.closing.offer": "ללא חשבון. ללא פרסומות.",
  
  "support.meta.title": "תמיכה של Pushanova",
  "support.meta.description": "מצאו תשובות לגבי אימונים, ספירת שכיבות סמיכה, Apple Watch, Apple Health, רכישות ופרטיות.",
  "support.h1": "תמיכה של Pushanova",
  "support.lead": "מצאו תשובות לגבי אימונים, ספירת שכיבות סמיכה, Apple Watch, Apple Health, רכישות ופרטיות.",
  "support.contactLead": "אם אתם עדיין צריכים עזרה, שלחו דוא״ל אל <a href=\"{mailto}\">{email}</a>.",
  
  "support.topics.h2": "נושאי תמיכה",
  "support.topics.items.0.href": "#getting-started",
  "support.topics.items.0.label": "תחילת הדרך",
  "support.topics.items.1.href": "#push-up-counting",
  "support.topics.items.1.label": "ספירת שכיבות סמיכה",
  "support.topics.items.2.href": "#apple-watch",
  "support.topics.items.2.label": "Apple Watch",
  "support.topics.items.3.href": "#apple-health-heart-rate-and-calories",
  "support.topics.items.3.label": "Apple Health, דופק וקלוריות",
  "support.topics.items.4.href": "#workouts-and-progress",
  "support.topics.items.4.label": "אימונים והתקדמות",
  "support.topics.items.5.href": "#premium-and-purchases",
  "support.topics.items.5.label": "פרימיום ורכישות",
  "support.topics.items.6.href": "#privacy-and-data",
  "support.topics.items.6.label": "פרטיות ונתונים",
  "support.topics.items.7.href": "#devices-and-compatibility",
  "support.topics.items.7.label": "מכשירים ותאימות",
  "support.topics.items.8.href": "#troubleshooting",
  "support.topics.items.8.label": "פתרון תקלות",
  
  "support.sections.0.id": "getting-started",
  "support.sections.0.heading": "תחילת הדרך",
  "support.sections.0.items.0.question": "איך אני מתחיל אימון?",
  "support.sections.0.items.0.answer": "<p>ב-iPhone או ב-iPad, פתחו את כרטיסיית <strong>אימונים</strong>. הכותרת בראש המסך היא <strong>שכיבות סמיכה</strong>.</p><ul><li>הקישו על <strong>רמה</strong> כדי להשלים אימון מובנה מהתוכנית.</li><li>הקישו על <strong>Freestyle</strong> כדי להתאמן ללא סטים מוגדרים מראש או יעדי שכיבות סמיכה.</li></ul><p>ספירה קצרה לאחור תיתן לכם זמן להיכנס לתנוחה. שכיבת הסמיכה הראשונה שלכם מתחילה את הסט הראשון.</p><p>ב-Apple Watch, פתחו את Pushanova והקישו על <strong>רמה</strong> או <strong>Freestyle</strong>.</p>",
  "support.sections.0.items.1.question": "איך אני בוחר רמה?",
  "support.sections.0.items.1.answer": "<p>ב-iPhone או ב-iPad, פתחו את <strong>אימונים</strong> והקישו על <strong>בחירת רמה</strong>. ב-Apple Watch, הקישו על <strong>בחירה</strong> ליד 'רמה'.</p><p>התוכנית כוללת 50 רמות בשלושה שלבים. תוכלו להתחיל בכל רמה שזמינה עבורכם. השלמת שכיבות הסמיכה הנדרשות מקדמת את התוכנית לרמה הבאה.</p><p>רמות 1–10 הן בחינם. רמות 11–50 דורשות Pushanova Premium.</p>",
  "support.sections.0.items.2.question": "איך מתאמנים ללא התוכנית?",
  "support.sections.0.items.2.answer": "<p>התחילו <strong>Freestyle</strong> ב-iPhone, ב-iPad או ב-Apple Watch. אתם מחליטים כמה שכיבות סמיכה וסטים לבצע.</p><p>כאשר Pushanova מזהה מנוחה, היא מסיימת את הסט הנוכחי. שכיבת הסמיכה הבאה שלכם תתחיל סט חדש. הקישו על <strong>סיום אימון</strong> כשתסיימו. תוכלו גם להמשיך בחופשיות לאחר שתסיימו רמה באותו האימון.</p>",
  "support.sections.0.items.3.question": "מה משמעות התיבות של הסטים?",
  "support.sections.0.items.3.answer": "<p>ב-iPhone וב-iPad, שורת <strong>סטים</strong> מציגה את הסטים באימון הנוכחי. כל תיבה מייצגת סט אחד.</p><p>במהלך אימון תוכנית:</p><ul><li>תיבות קרובות מציגות את יעדי שכיבות הסמיכה המתוכננים.</li><li>התיבה המודגשת מציגה את הסט הנוכחי.</li><li>המספר הגדול מציג כמה שכיבות סמיכה נותרו בסט המתוכנן הנוכחי.</li><li>תיבה שהושלמה מציגה כמה שכיבות סמיכה ביצעתם.</li><li>סטים נוספים מופיעים לאחר שתמשיכו מעבר ליעד התוכנית.</li></ul><p>כשאתם מתאמנים באופן חופשי, כל תיבה מופיעה לאחר ש-Pushanova מסיימת סט. המספר הגדול מציג את ספירת שכיבות הסמיכה בסט הנוכחי.</p><p>תוכלו לגלול בשורה כשהיא מכילה הרבה סטים. ה-Apple Watch מציג טקסט כמו <strong>סט 2 מתוך 5</strong> במקום תיבות.</p>",
  "support.sections.0.items.4.question": "איך עליי למקם את ה-iPhone או ה-iPad שלי?",
  "support.sections.0.items.4.answer": "<p>לספירת מצלמה אוטומטית, הניחו את המכשיר שטוח על הרצפה כאשר המסך פונה כלפי מעלה. שמרו את המצלמה הקדמית מתחת לפניכם, השתמשו בתאורה טובה, ושמרו את הפנים שלכם בשדה הראייה. אל תניחו את המכשיר בזווית.</p><p>אם הגישה למצלמה אינה זמינה ב-iPhone, הניחו את הקצה העליון של הטלפון קרוב לפניכם. המסך עשוי להשחיר לזמן קצר כשהפנים שלכם קרובים. זה תקין.</p><p>אם אינכם משתמשים בגישה למצלמה ב-iPad, הפעילו את <strong>הקש כדי לספור</strong> והקישו על המסך עבור כל שכיבת סמיכה.</p>"
};

Object.assign(translations, {
  "support.sections.1.id": "push-up-counting",
  "support.sections.1.heading": "ספירת שכיבות סמיכה",
  "support.sections.1.items.0.question": "באילו סוגים של שכיבות סמיכה יש תמיכה?",
  "support.sections.1.items.0.answer": "<p>iPhone ו-iPad תומכים בשכיבות סמיכה רגילות על הרצפה ובשכיבות סמיכה מהברכיים.</p><p>Apple Watch תומך בשכיבות סמיכה על הרצפה ובשכיבות סמיכה מוגבהות על ספסל או מוט אופקי.</p><p>שכיבות סמיכה על ידיות מקבילות עם כפות הידיים פונות זו לזו אינן נתמכות. שכיבות סמיכה על האגרופים עשויות לעבוד, אך הספירה עלולה להיות פחות מדויקת.</p>",
  "support.sections.1.items.1.question": "מה עלי לעשות אם Pushanova מפספסת או מוסיפה שכיבות סמיכה?",
  "support.sections.1.items.1.answer": "<p>ספירה אוטומטית עשויה לפספס או להוסיף שכיבות סמיכה. מיקום המכשיר, תאורה, תנועה, יציבה ומהירות יכולים להשפיע על התוצאה.</p><p>ב-iPhone או ב-iPad:</p><ul><li>הניחו את המכשיר שטוח על הרצפה.</li><li>שמרו את הפנים שלכם גלויות למצלמה הקדמית.</li><li>השתמשו בתאורה טובה.</li><li>השלימו תנועה ברורה כלפי מטה וכלפי מעלה.</li><li>הרחיקו תנועות אחרות מהמצלמה.</li></ul><p>ב-Apple Watch:</p><ul><li>ענדו את הרצועה בצורה יציבה ונוחה.</li><li>השלימו תנועה ברורה כלפי מטה וכלפי מעלה.</li><li>הימנעו מהזזת זרוע ה-Watch בנפרד משכיבת הסמיכה.</li></ul><p>תוכלו להשתמש ב<strong>הקש כדי לספור</strong> כאשר הספירה האוטומטית אינה מתאימה. לאחר האימון, תוכלו לתקן את הספירות של סטים שהושלמו.</p>",
  "support.sections.1.items.2.question": "מה עלי לעשות אם ספירה אוטומטית אינה עובדת כלל?",
  "support.sections.1.items.2.answer": "<ol><li>אשרו שהמכשיר נמצא במיקום הנכון.</li><li>ב-iPhone או ב-iPad, בדקו את הגישה למצלמה עבור Pushanova.</li><li>ב-Apple Watch, בדקו את הגישה ל-Apple Health וענדו את ה-Watch בצורה יציבה על פרק כף היד שלכם.</li><li>סגרו ופתחו מחדש את Pushanova.</li><li>התחילו אימון בדיקה קצר.</li><li>אם הספירה עדיין אינה עובדת, השתמשו ב<strong>דיווח על בעיה</strong> מתוך האימון שהושלם.</li></ol><p>ב-iPad ללא גישה למצלמה, השתמשו ב<strong>הקש כדי לספור</strong>.</p>",
  "support.sections.1.items.3.question": "מדוע מסך ה-iPhone שלי משחיר לזמן קצר?",
  "support.sections.1.items.3.answer": "<p>כאשר גישה למצלמה אינה זמינה, ה-iPhone יכול להשתמש בשיטת ספירה מובנית אחרת. המסך עשוי להשחיר לזמן קצר כאשר הפנים שלכם קרובות לחלק העליון של הטלפון.</p><p>זה תקין ואינו אומר ש-Pushanova מצלמת תמונות או מקליטה וידאו.</p>",
  "support.sections.1.items.4.question": "איך אני סופר שכיבות סמיכה על ידי הקשה על המסך?",
  "support.sections.1.items.4.answer": "<p>פתחו את <strong>הגדרות</strong> ב-Pushanova והפעילו את <strong>הקש כדי לספור</strong>. במהלך אימון, כל הקשה על מסך האימון סופרת שכיבת סמיכה אחת.</p>",
  "support.sections.1.items.5.question": "האם אני יכול לתקן או להוסיף שכיבות סמיכה לאחר אימון?",
  "support.sections.1.items.5.answer": "<p>ניתן לתקן את מספר שכיבות הסמיכה בסטים שכבר קיימים. פתחו את האימון, הקישו על עריכה בתרשים שכיבות הסמיכה, שנו את ספירות הסטים, והקישו על שמירה.</p><p>העריכה אינה מוסיפה סט נוסף לאימון. כדי לתעד עבודה נוספת כמפגש נפרד, פתחו את <strong>אימונים</strong>, הקישו על <strong>הוספת אימון</strong>, והזינו את הסטים ידנית.</p>",
  "support.sections.1.items.6.question": "מה כלול בדיווח על בעיית ספירה?",
  "support.sections.1.items.6.answer": "<p>פתחו אימון שהושלם ובחרו ב<strong>דיווח על בעיה</strong>. תוכלו לתאר את הבעיה ולספק את ספירות שכיבות הסמיכה שציפיתם להן.</p><p>הדיווח עשוי לכלול מדידות תנועה, ספירות שכיבות סמיכה, נתוני תזמון, מידע על המכשיר, גרסת יישום ושפה. הוא אינו כולל תמונות או וידאו.</p><p>הדיווח נשלח בדוא״ל רק כאשר אתם בוחרים לשלוח אותו.</p>",
  
  "support.sections.2.id": "apple-watch",
  "support.sections.2.heading": "Apple Watch",
  "support.sections.2.items.0.question": "האם אני יכול להשתמש ב-Pushanova ב-Apple Watch ללא ה-iPhone שלי?",
  "support.sections.2.items.0.answer": "<p>כן. ניתן להתחיל ולהשלים אימון ב-Apple Watch ללא ה-iPhone בקרבת מקום. פתחו את Pushanova ב-Watch והקישו על <strong>רמה</strong> או <strong>Freestyle</strong>.</p><p>גישה ל-Apple Health נדרשת עבור אימוני Watch.</p><p>היישום ב-Watch מתמקד באימונים פעילים ובסיכום שמוצג מיד לאחר מכן. השתמשו ב-Pushanova ב-iPhone או ב-iPad עבור היסטוריית אימונים מלאה, לוח שנה, התקדמות, עריכה, דיווח על בעיות ושיתוף.</p>",
  "support.sections.2.items.1.question": "איך אני משתמש ב-Apple Watch וב-iPhone יחד?",
  "support.sections.2.items.1.answer": "<p>ב-iPhone, פתחו את <strong>הגדרות</strong> ב-Pushanova והפעילו את <strong>שימוש ב-Apple Watch</strong>. ודאו ש-Pushanova מותקנת ב-Watch ושה-Watch פתוח ונמצא בקרבת מקום. לאחר מכן, התחילו את האימון ב-iPhone או ב-Apple Watch.</p><p>ה-Apple Watch סופר את שכיבות הסמיכה שלכם בעוד ה-iPhone מציג את אותו האימון. ספירת שכיבות סמיכה, סטים, קצב, ומנוחה נשארים מסונכרנים.</p><p>אימוני Apple Watch מצומדים זמינים עם iPhone, לא עם iPad.</p>",
  "support.sections.2.items.2.question": "למה אימון לא מתחיל ב-Apple Watch?",
  "support.sections.2.items.2.answer": "<p>בדקו את הדברים הבאים:</p><ul><li>ניתנה גישה ל-Apple Health עבור Pushanova ב-Watch.</li><li>אין אימון אחר שרץ כעת ב-Watch.</li><li>ה-Watch לא נעול.</li><li>Pushanova מותקנת ב-Watch.</li></ul><p>אם התחלתם מה-iPhone ואתם רואים <strong>Apple Watch לא מגיב</strong>, בדקו אם האימון כבר פתוח ב-Watch. אחרת, פתחו את Pushanova ב-Watch ונסו שוב.</p>",
  "support.sections.2.items.3.question": "למה אימון ה-Apple Watch שלי חסר ב-iPhone או ב-iPad?",
  "support.sections.2.items.3.answer": "<p>Pushanova שומרת את רשומת האימון שלה בנפרד מ-Apple Health. כאשר סנכרון iCloud מופעל, רשומות אימונים של Pushanova מסתנכרנות דרך חשבון ה-iCloud האישי שלכם. העותק ב-Apple Health הוא אימון כוח נפרד.</p><p>אשרו ש:</p><ul><li>האימון כלל לפחות שכיבת סמיכה אחת שנספרה.</li><li>האימון הגיע לסיכום שלו.</li><li>המכשירים שלכם משתמשים באותו חשבון Apple Account.</li><li>iCloud מופעל עבור Pushanova.</li><li>לשני המכשירים יש חיבור לאינטרנט.</li></ul><p>פתחו את Pushanova ב-iPhone או ב-iPad ואפשרו זמן לסנכרון. אם האימון מופיע ב-Apple Health אך לא ב-Pushanova, כללו מידע זה בעת הפנייה לתמיכה.</p>",

  "support.sections.3.id": "apple-health-heart-rate-and-calories",
  "support.sections.3.heading": "Apple Health, דופק וקלוריות",
  "support.sections.3.items.0.question": "האם Apple Health חובה?",
  "support.sections.3.items.0.answer": "<p>Apple Health היא אופציונלית ב-iPhone וב-iPad. ללא Apple Health, Pushanova עדיין סופרת שכיבות סמיכה, שומרת אימונים ביישום ומעריכה קלוריות פעילות.</p><p>גישה ל-Apple Health נדרשת כדי להתחיל אימון ב-Apple Watch.</p>",
  "support.sections.3.items.1.question": "איך אני נותן ל-Pushanova גישה ל-Apple Health?",
  "support.sections.3.items.1.answer": "<p>פתחו את הגדרות הגישה של הבריאות עבור Pushanova ביישום הבריאות או ביישום ההגדרות של המערכת. עברו על הקטגוריות ש-Pushanova יכולה לקרוא ולכתוב.</p><p>Pushanova מבקשת רק את הקטגוריות הנדרשות עבור אימונים, דופק, קלוריות פעילות, והערכות קלוריות. תוכלו לשנות את הגישה מאוחר יותר ב-Apple Health או ביישום ההגדרות של המערכת.</p>",
  "support.sections.3.items.2.question": "מה Pushanova שומרת ב-Apple Health?",
  "support.sections.3.items.2.answer": "<p>באישורכם, Pushanova שומרת אימון כוח שהושלם וקלוריות פעילות ב-Apple Health. משך הזמן ודופק נכללים כשהם זמינים.</p><p>ספירת שכיבות סמיכה וסטים נשארים ב-Pushanova. Apple Health אינה שומרת את הספירות האלה.</p><p>Pushanova יכולה לקרוא מידע נתמך של Apple Health, כגון דופק, קלוריות פעילות ומסת גוף, כאשר אתם מאשרים זאת. מידע זה משמש לאימונים ולהערכות קלוריות.</p>",
  "support.sections.3.items.3.question": "למה האימון שלי חסר ב-Apple Health?",
  "support.sections.3.items.3.answer": "<p>בדקו את הדברים הבאים:</p><ul><li>גישה ל-Apple Health מאפשרת ל-Pushanova לשמור אימונים.</li><li>האימון כלל לפחות שכיבת סמיכה אחת שנספרה.</li><li>השלמתם את האימון והגעתם לסיכום.</li><li>לא הופיעה שגיאת שמירה במסך הסיכום.</li></ul><p>ב-Apple Watch, הגישה לבריאות חייבת להישאר מופעלת במהלך האימון.</p>",
  "support.sections.3.items.4.question": "אילו מכשירים יכולים לספק דופק?",
  "support.sections.3.items.4.answer": "<p>נתוני דופק יכולים להגיע מ:</p><ul><li>Apple Watch במהלך אימון ב-Watch עם Pushanova</li><li>אוזניות תומכות מד דופק</li><li>מד דופק Bluetooth המחובר דרך Apple Watch, iPhone או iPad</li></ul><p>Pushanova אינה מצמדת ישירות מכשירי מדידת דופק. חברו מכשירים נתמכים דרך ההגדרות של Apple.</p><p>מדידת דופק עם אוזניות נתמכות דורשת iOS 26 ואילך ב-iPhone, או iPadOS 26 ואילך ב-iPad.</p>",
  "support.sections.3.items.5.question": "למה הדופק חסר?",
  "support.sections.3.items.5.answer": "<p>אשרו ש:</p><ul><li>Pushanova יכולה לקרוא דופק ב-Apple Health.</li><li>ה-Apple Watch ענוד בצורה יציבה ונוחה.</li><li>מכשיר מדידת דופק תואם מחובר ופעיל במהלך האימון.</li></ul><p>אפשרו זמן קצר למידע הדופק להופיע לאחר תחילת האימון. אימון ב-iPhone או ב-iPad עשוי שלא להראות דופק כאשר אף מקור תואם אינו מספק אותו.</p>",
  "support.sections.3.items.6.question": "כיצד מחושבות קלוריות פעילות?",
  "support.sections.3.items.6.answer": "<p>Pushanova משתמשת בקלוריות פעילות מ-Apple Health כשהן זמינות. אחרת, Pushanova מעריכה קלוריות פעילות מתוך מידע האימון הזמין.</p><p>הערכה זו אינה דורשת מידע על דופק. מתן אישור ל-Pushanova לקרוא את המשקל שלכם מ-Apple Health יכול לשפר את ההערכה.</p><p>תרשימים מפורטים של דופק, קצב ותדירות דורשים Pushanova Premium. האימון והסיכום הבסיסי נשמרים עדיין ללא Premium.</p>"
});
Object.assign(translations, {
  "support.sections.4.id": "workouts-and-progress",
  "support.sections.4.heading": "אימונים והתקדמות",
  "support.sections.4.items.0.question": "למה האימון שלי לא נשמר או מופיע בהיסטוריה?",
  "support.sections.4.items.0.answer": "<p>Pushanova אינה שומרת אימון עם אפס שכיבות סמיכה שנספרו. אימון שבוטל או נזרק גם הוא אינו נשמר.</p><p>גורמים אפשריים אחרים כוללים שטח אחסון לא מספיק במכשיר או סגירת היישום בזמן שהאימון נשמר. אם השמירה נכשלת, הסיכום מסביר שהאימון לא יופיע בהיסטוריה.</p><p>אם סנכרון iCloud מופעל, אפשרו זמן לאימון שהושלם להופיע במכשירים האחרים שלכם. Apple Health שומרת עותק נפרד ואינה המקור לסנכרון אימונים של Pushanova.</p>",
  "support.sections.4.items.1.question": "Pushanova נסגרה במהלך אימון. האם אוכל לשחזר אותו?",
  "support.sections.4.items.1.answer": "<p>לרוב כן. פתחו מחדש את Pushanova ועקבו אחר הודעת השחזור. ב-Apple Watch, עשוי להופיע התראה על הפרעה באימון, ושחרור ההודעה שומר את החלק שהושלם במידת האפשר.</p><p>ייתכן שלא יהיה ניתן לשחזר כאשר האימון השמור פגום, ישן מדי, או שלמכשיר אין מספיק שטח אחסון פנוי. אם הבעיה נמשכת:</p><ul><li>עדכנו את Pushanova ואת מערכת ההפעלה של המכשיר.</li><li>הפעילו מחדש את המכשיר.</li><li>אשרו שלמכשיר יש שטח אחסון פנוי.</li><li>אל תסגרו את Pushanova בזמן שסיום אימון נשמר.</li></ul>",
  "support.sections.4.items.2.question": "איך אני מוסיף אימון באופן ידני?",
  "support.sections.4.items.2.answer": "<p>פתחו את כרטיסיית <strong>אימונים</strong>, הקישו על <strong>הוספת אימון</strong>, והזינו את הסטים ושכיבות הסמיכה שביצעתם.</p><p>אימונים ידניים אינם כוללים זמני מנוחה, קצב או דופק. הם אינם נשמרים ב-Apple Health.</p>",
  "support.sections.4.items.3.question": "האם אני יכול למחוק אימון?",
  "support.sections.4.items.3.answer": "<p>כן. פתחו את כרטיסיית <strong>אימונים</strong> והחליקו שמאלה על האימון שברצונכם למחוק. תוכלו גם למחוק אימון מתוך מסך הפרטים שלו.</p><p>מחיקת אימון מסירה אותו מכל המכשירים המשתמשים באותו חשבון iCloud. מחיקת אימון מ-Pushanova אינה מוחקת אותו מ-Apple Health.</p>",
  "support.sections.4.items.4.question": "האם ניתן להסיר את הסטים המתוכננים מאימון רמה?",
  "support.sections.4.items.4.answer": "<p>לא, אך תוכלו להתאמן באופן חופשי מתי שתרצו. תוכנית 100 שכיבות הסמיכה נועדה לעקוב אחר סדר מסוים. אם אינכם רוצים סטים ויעדים מתוכננים, השתמשו באפשרות <strong>Freestyle</strong>.</p>",

  "support.sections.5.id": "premium-and-purchases",
  "support.sections.5.heading": "פרימיום ורכישות",
  "support.sections.5.items.0.question": "האם Pushanova היא בחינם?",
  "support.sections.5.items.0.answer": "<p>כן. האימון בחינם כולל ספירה אוטומטית, אימונים חופשיים ללא הגבלה, ואת 10 רמות התוכנית הראשונות.</p><p>סנכרון iCloud, אינטגרציה עם Apple Health, ויישומי ה-Apple Watch וה-iPad הם גם בחינם. Pushanova אינה מכילה פרסומות.</p>",
  "support.sections.5.items.1.question": "מה כלול ב-Pushanova Premium?",
  "support.sections.5.items.1.answer": "<p>Pushanova Premium פותח את רמות התוכנית 11–50 ומספק דרכים נוספות לסקור את ההתקדמות שלכם. אלה כוללים:</p><ul><li>לוח שנת אימונים שבו תוכלו לראות אימונים קודמים במבט חטוף.</li><li>השוואות שבועיות של סך שכיבות הסמיכה והאימונים.</li><li>תרשימים מפורטים עבור שכיבות סמיכה, קצב, פעילות ודופק על פני תקופות זמן ארוכות יותר.</li><li>פרטי קצב, תדירות ודופק עבור כל אימון וסט בודדים.</li></ul>",
  "support.sections.5.items.2.question": "האם אני צריך מינוי כדי להשתמש ב-Pushanova Premium?",
  "support.sections.5.items.2.answer": "<p>לא. Pushanova Premium זמינה כמינוי שנתי וכרכישה חד-פעמית לכל החיים.</p><p>שתי האפשרויות פותחות את אותן התכונות. הרכישה לכל החיים אינה פגה ואינה דורשת תשלומים נוספים.</p>",
  "support.sections.5.items.3.question": "האם יש תקופת ניסיון בחינם עבור Pushanova Premium?",
  "support.sections.5.items.3.answer": "<p>מנויים חדשים זכאים עשויים לקבל תקופת ניסיון בחינם למשך שלושה ימים עם המינוי השנתי. מסך Pushanova Premium מציג אם תקופת הניסיון זמינה עבור חשבון ה-Apple Account שלכם.</p><p>המינוי השנתי מתחיל אוטומטית לאחר תקופת הניסיון אלא אם כן תבטלו לפחות 24 שעות לפני תום התקופה. Apple מנהלת את הזכאות, החיוב והחידוש.</p><p>הרכישה לכל החיים אינה כוללת תקופת ניסיון בחינם.</p>",
  "support.sections.5.items.4.question": "איך אני מבטל מינוי?",
  "support.sections.5.items.4.answer": "<p>מינויים מנוהלים על ידי Apple, לא על ידי יישומים בודדים. תוכלו לבטל מינוי בהגדרות של Apple.</p><p>ב-iPhone או ב-iPad, פתחו את יישום <strong>הגדרות</strong> המובנה של המערכת, הקישו על השם שלכם בחלק העליון, ולאחר מכן הקישו על <strong>מינויים</strong>. בחרו ב-Pushanova ופעלו לפי ההוראות שעל המסך.</p><p>ביטול עוצר את החידוש האוטומטי, ותשמרו על הגישה לתכונות ה-Premium עד תום תקופת החיוב הנוכחית.</p>",
  "support.sections.5.items.5.question": "איך אני מבקש החזר כספי?",
  "support.sections.5.items.5.answer": "<p>כל הרכישות מנוהלות ומחויבות על ידי Apple. מפתחים אינם יכולים לעבד החזרים כספיים.</p><p>כדי לבקש החזר כספי, בקרו באתר התמיכה של Apple בכתובת <a href=\"https://reportaproblem.apple.com/\">reportaproblem.apple.com</a>. היכנסו עם ה-Apple Account שלכם, בחרו <strong>בקש החזר כספי</strong>, ובחרו ב-Pushanova מהרשימה.</p>",
  "support.sections.5.items.6.question": "האם אני יכול להשתמש ב-Pushanova Premium במכשירים אחרים שלי?",
  "support.sections.5.items.6.answer": "<p>כן. הרכישה שלכם מקושרת ל-Apple Account שלכם. כל מכשיר המחובר לאותו Apple Account יכול לגשת ל-Pushanova Premium.</p><p>אם התכונות אינן זמינות במכשיר השני, הקישו על <strong>שחזור רכישה</strong> במסך Pushanova Premium כדי לאמת את הגישה שלכם.</p>",
  "support.sections.5.items.7.question": "האם Pushanova Premium תומכת בשיתוף משפחתי (Family Sharing)?",
  "support.sections.5.items.7.answer": "<p>כן. המינוי השנתי והרכישה לכל החיים תומכים שניהם בשיתוף משפחתי של Apple. אם שיתוף משפחתי מוגדר בחשבון ה-Apple Account שלכם, בני המשפחה שלכם יכולים לגשת לתכונות ה-Premium.</p><p>ייתכן שבני משפחה יצטרכו להקיש על <strong>שחזור רכישה</strong> במסך Pushanova Premium כדי להפעיל את הגישה שלהם.</p>",
  "support.sections.5.items.8.question": "איך אני משתמש בקוד הטבה?",
  "support.sections.5.items.8.answer": "<p>פתחו את <strong>הגדרות</strong> ב-Pushanova ב-iPhone והקישו על <strong>מימוש הטבה</strong>. Apple Watch אינו יכול לממש קוד הטבה.</p><p>Apple קובעת אם הקוד תקין ולאיזה חשבון Apple Account מותר להשתמש בו.</p>",

  "support.sections.6.id": "privacy-and-data",
  "support.sections.6.heading": "פרטיות ונתונים",
  "support.sections.6.items.0.question": "האם Pushanova מצלמת תמונות או וידאו?",
  "support.sections.6.items.0.answer": "<p>לא. ספירה אוטומטית אינה מצלמת תמונות או מקליטה, שומרת או מעלה וידאו. Pushanova אינה משתמשת במצלמה כדי לזהות אתכם.</p><p>תמונות לאחר האימון הן בנפרד. Pushanova משתמשת בתמונה רק כאשר אתם בוחרים אחת לשיתוף.</p>",
  "support.sections.6.items.1.question": "היכן נשמרים הנתונים שלי?",
  "support.sections.6.items.1.answer": "<p>נתוני האימון נשמרים במכשיר שלכם. כאשר סנכרון iCloud מופעל, הנתונים שלכם מסתנכרנים באופן מאובטח בין המכשירים שלכם באמצעות חשבון ה-iCloud האישי שלכם.</p><p>Pushanova אינה מאחסנת את נתוני האימון שלכם בשרתים שלה.</p>",
  "support.sections.6.items.2.question": "האם Pushanova מוכרת את הנתונים שלי או מציגה פרסומות?",
  "support.sections.6.items.2.answer": "<p>לא. Pushanova אינה מוכרת את הנתונים שלכם לאף אחד ואינה מכילה פרסומות.</p>",
  "support.sections.6.items.3.question": "האם אני צריך ליצור חשבון Pushanova?",
  "support.sections.6.items.3.answer": "<p>לא. Pushanova אינה דורשת הרשמה, שם משתמש, סיסמה או התחברות דרך רשת חברתית.</p><p>Pushanova Premium מחוברת לחשבון ה-Apple Account ששימש לרכישה ב-App Store. זהו אינו חשבון Pushanova.</p>",
  "support.sections.6.items.4.question": "איזה מידע אוספת Pushanova?",
  "support.sections.6.items.4.answer": "<p>Pushanova משתמשת בשירותי אנליטיקה ודיווח קריסות סטנדרטיים של מוצרים. שירותים אלו אינם מקבלים תמונות, וידאו, מדידות ספירה מבוססות מצלמה, או מידע מ-Apple Health.</p><p>Pushanova אינה מוכרת את הנתונים שלכם ואינה משתמשת בהם לצורכי פרסום.</p><p>קראו את <a href=\"{privacyUrl}\">מדיניות הפרטיות</a> לפרטים.</p>",
  
  "support.sections.7.id": "devices-and-compatibility",
  "support.sections.7.heading": "מכשירים ותאימות",
  "support.sections.7.items.0.question": "אילו מכשירים נתמכים?",
  "support.sections.7.items.0.answer": "<ul><li>iPhone: iOS 17.6 ואילך</li><li>iPad: iPadOS 17.6 ואילך</li><li>Apple Watch: watchOS 10.6 ואילך</li></ul><p>כל מכשיר שיכול להריץ גרסה נתמכת יכול להתקין את Pushanova. שיטות הספירה הזמינות תלויות במכשיר ובהרשאות שאתם מספקים.</p>",
  "support.sections.7.items.1.question": "האם Pushanova תעבוד על מכשיר ה-Android שלי?",
  "support.sections.7.items.1.answer": "<p>לא. Pushanova נבנתה במיוחד עבור מכשירי Apple וזמינה רק עבור iPhone, iPad, ו-Apple Watch.</p>",

  "support.sections.8.id": "troubleshooting",
  "support.sections.8.heading": "פתרון תקלות",
  "support.sections.8.items.0.question": "היישום לא פועל כצפוי. מה עליי לעשות?",
  "support.sections.8.items.0.answer": "<p>נסו את השלבים הבאים, שלעתים קרובות פותרים בעיות נפוצות:</p><ol><li>סגרו והפעילו מחדש את היישום במכשיר שבו מתרחשת הבעיה.</li><li>ודאו שהתקנתם את הגרסה האחרונה של Pushanova מה-App Store.</li><li>בדקו אם יש עדכוני תוכנה במכשיר ה-Apple שלכם.</li><li>הפעילו מחדש את ה-iPhone, ה-iPad, או ה-Apple Watch שלכם.</li></ol>",
  "support.sections.8.items.1.question": "איך אני מדווח על בעיה או שולח משוב?",
  "support.sections.8.items.1.answer": "<p>כדי לדווח על בעיה בספירת שכיבות סמיכה, פתחו את האימון שהושלם והשתמשו ב<strong>דיווח על בעיה</strong>.</p><p>למשוב כללי או לשאלות אחרות, שלחו דוא״ל אל <a href=\"{mailto}\">{email}</a>.</p>",
  
  "support.sections.8.body": "הגדר חשבון דוא״ל ביישום ״הגדרות״, או שלח את ההודעה ידנית אל {email}."
});

function buildTranslated(obj, path="") {
  const result = {};
  for (let key in obj) {
    if (obj[key] && typeof obj[key] === "object" && obj[key].hasOwnProperty("message")) {
      const fullPath = path + key;
      if (translations.hasOwnProperty(fullPath)) {
        result[key] = { message: translations[fullPath] };
      } else {
        console.error("Missing translation for:", fullPath);
        result[key] = { message: obj[key].message }; // fallback
      }
    } else if (obj[key] && typeof obj[key] === "object") {
      result[key] = buildTranslated(obj[key], path + key + ".");
    }
  }
  return result;
}

const heJson = buildTranslated(en);
fs.writeFileSync('locales/he.json', JSON.stringify(heJson, null, 2));
console.log("Wrote locales/he.json");
